[package]
name = "test-task"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.20.1", features = ["fs", "rt", "macros", "io-util", "rt-multi-thread"] }